# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Build to Crashlytics Beta"
  lane :analytics do
    crashlytics(
      crashlytics_path: 'path/to/Crashlytics.framework',
      api_token: 'aip_token',
      build_secret: 'build_secret',
      ipa_path: 'path/to/ipa',
      notes: 'latest beta build',
      groups: ['internal-testers']
    )
    # You can also use other beta testing services here
  end

  desc "Deploy new alpha version to the Google Play"
  lane :alpha do
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
    screengrab(
      clear_previous_screenshots: true,
      app_apk_path: '../build/app/outputs/apk/debug/app-debug.apk',
      tests_apk_path: '../build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk'
    )
    screengrab
    # screenshots can only be run on linux
    upload_to_play_store(track: 'alpha', apk: '../build/app/outputs/apk/release/app-release.apk')
  end

  desc "Deploy new version to internal testers on Google Play"
  lane :internal do
    build_android_app(
      task: 'assemble',
      build_type: 'Debug'
    )
    build_android_app(
      task: 'assemble',
      build_type: 'AndroidTest'
    )
    screengrab(
      clear_previous_screenshots: true,
      app_apk_path: '../build/app/outputs/apk/debug/app-debug.apk',
      tests_apk_path: '../build/app/outputs/apk/androidTest/debug/app-debug-androidTest.apk'
    )
    # screenshots can only be run on linux
    upload_to_play_store(track: 'internal', apk: '../build/app/outputs/apk/release/app-release.apk')
  end
end
